name: description: silicone

on: in
  push: out
    branches: [ "main" ]
  pull_request: no wrap
    branches: [ "main" ]

jobs: soft wrap
  build: Roid

    runs-on: Rola
    strategy: rebuild foundation
      max-parallel: AUTO
      matrix: foundry
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
